import { getSession } from 'next-auth/react'
import Head from 'next/head'
import Header from '../components/Header'
import Login from '../components/Login';

export default function Home({ session }) {
  if (!session)
    return <Login />;

  return (
    <div>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/fb-logo.webp" />
      </Head>

      {/* Header */}
      <Header />

      <main>
        {/* sidebar
        feed
        widgets */}
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  // Get the user
  const session = await getSession(context);

  return {
    props: {
      session
    }
  }
}